### ISSUE TITLE
Avatar not displaying

### ISSUE THREAD

**Issue by EternalIllusion** [D-Sketon/hugo-theme-reimu#1]
I placed avatar.webp in /static /static/avatar /static/images but it didn't work on Android(on PCs it works). In params.yml I set avatar: "avatar.webp"
Modifed theme at https://github.com/EternalIllusion/hugo-theme-reimu
Issue site:eternalillusion.github.io
Issue device: Android 8.1.0 Edge
BTW, git submodule may not work when installing so I forked the repo.
Pls help me AwA
Screenshot :
![Screenshot_20241212-204233](https://github.com/user-attachments/assets/147408a3-110e-412d-b9d3-c812deb320c6)

**Comment by EternalIllusion** [comment]
Also, the cover won't display too

**Comment by D-Sketon** [comment]
I have checked your site, the avatar is now loading properly
![{21AC5ACD-4684-4FDD-BC24-9B3D458435DE}](https://github.com/user-attachments/assets/4f00c250-6ab2-453e-adbc-72e5c9cf4176)
the avatar url is https://eternalillusion.github.io/avatar/avatar.webp

**Comment by EternalIllusion** [comment]
This Issue **only** appears on Android devices’ edge browser.
On chrome on Android the side bar didn't work and posts even don't display.
On Windows OS it just doesn't appear.
Screen shot on Android chrome:
![Screenshot_20241213-072444](https://github.com/user-attachments/assets/5db8a023-a1f4-4b4d-b118-8eb41c966329)
Screen shot on Android Edge:
![Screenshot_20241213-070556](https://github.com/user-attachments/assets/455c7879-c165-4384-9a27-eda445eacf16)

**Comment by D-Sketon** [comment]
Android edge 130.0.2849.80
![Screenshot_2024-12-13-08-14-17-594_com.microsoft.emmx.jpg](https://github.com/user-attachments/assets/07601d31-9c53-4c00-b794-e17f72c21811)
Android Chrome 131.0.6778.135
![Screenshot_2024-12-13-08-19-42-204_com.android.chrome.jpg](https://github.com/user-attachments/assets/fe9fe6dc-3631-4bd4-bc8f-2471cff311fb)
Android xiaomi 
![Screenshot_2024-12-13-08-20-18-629_com.android.browser.jpg](https://github.com/user-attachments/assets/9a3f63de-b106-4e34-88fc-0ea714e20313)

**Comment by D-Sketon** [comment]
edge and chrome use the same kernel, so theoretically the effect should be the same!
I'm guessing there may be a network issue that is causing some of the js to not load successfully (avatars need lazysizes.js)

**Comment by EternalIllusion** [comment]
Thanks.There seemed some issues on my emulator's network.
Anyway, thx for helping me.
